In [1131]:
import importlib
import theano.tensor as T
import sys, os
sys.path.append("/home/bl3/PycharmProjects/GeMpy/")
import GeoMig
#importlib.reload(GeoMig)
importlib.reload(GeoMig)
import numpy as np

In [1132]:
layer_1 = np.array([[1,7],[5,7],[6,7], [9,8]], dtype = "float64")

layer_2 = np.array([[1,1],[5,1],[9,1]], dtype = "float64")

dip_pos_1 = np.array([2,4,], dtype = "float64")
dip_pos_2 = np.array([6.,3.], dtype = "float64")
dip_pos_3 = np.array([8,4], dtype = "float64")
#aux = np.vstack((layer_1[:],layer_2[:]))
#print (aux)
#a, b = np.tile(aux,(2,1,1)), np.shape(np.tile(aux,(2,1,1)))
#a, a.shape
test = GeoMig.GeoMigSim_pro2()
test.theano_set([layer_1, layer_2])

In [1133]:
test.theano_set()

In [1134]:
layers = np.asarray([layer_1,layer_2])
dips = np.asarray([dip_pos_1,dip_pos_2])#, dip_pos_3])

In [1135]:
layers.shape

(2,)

In [1136]:
#test.call_theano_for_CI([layer_1,layer_2])

In [1137]:
test.call_theano_for_CG(dips)

[array([[-0.58      ,  0.09102912, -0.58      , -0.01933956],
        [ 0.09102912, -0.58      , -0.01933956, -0.58      ],
        [-0.58      , -0.01933956, -0.58      ,  0.01850576],
        [-0.01933956, -0.58      ,  0.01850576, -0.58      ]]),
 array([[ 1.,  1.,  0.,  0.],
        [ 1.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  1.],
        [ 0.,  0.,  1.,  1.]])]

In [1129]:
test.call_theano_for_C_GI(dips,layers)

AttributeError: 'GeoMigSim_pro2' object has no attribute '_f_CGI'

In [1120]:
layers.squeeze()

array([ array([[ 1.,  7.],
       [ 5.,  7.],
       [ 6.,  7.],
       [ 9.,  8.]]),
       array([[ 1.,  1.],
       [ 5.,  1.],
       [ 9.,  1.]])], dtype=object)

In [1153]:
c = np.linspace(0,100,10 )
a= np.meshgrid(c,c)
a

[array([[   0.        ,   11.11111111,   22.22222222,   33.33333333,
           44.44444444,   55.55555556,   66.66666667,   77.77777778,
           88.88888889,  100.        ],
        [   0.        ,   11.11111111,   22.22222222,   33.33333333,
           44.44444444,   55.55555556,   66.66666667,   77.77777778,
           88.88888889,  100.        ],
        [   0.        ,   11.11111111,   22.22222222,   33.33333333,
           44.44444444,   55.55555556,   66.66666667,   77.77777778,
           88.88888889,  100.        ],
        [   0.        ,   11.11111111,   22.22222222,   33.33333333,
           44.44444444,   55.55555556,   66.66666667,   77.77777778,
           88.88888889,  100.        ],
        [   0.        ,   11.11111111,   22.22222222,   33.33333333,
           44.44444444,   55.55555556,   66.66666667,   77.77777778,
           88.88888889,  100.        ],
        [   0.        ,   11.11111111,   22.22222222,   33.33333333,
           44.44444444,   55.55555556,   

In [1155]:
T.sum?

In [1064]:
layers = np.asarray([layer_1,layer_2])
dips = np.asarray([dip_pos_1,dip_pos_2])

#==============================
dips2 = np.vstack((i for i in dips))
aux_X2 = np.vstack((np.tile(i[0], (np.shape(i)[0] - 1, 1)) for i in layers))
aux_Y2 = np.vstack((i[1:] for i in layers))
print ("aux",aux_X2, aux_Y2,aux_X2.shape, aux_Y2.shape)
print ("dips", dips)
#==============================
aux_X = T.dmatrix("aux_X")
aux_Y = T.dmatrix("aux Y")
dips = T.dmatrix("dips")
a = theano.shared(6)
# ========================================
# THE INTERACTION GRADIENTS/INTERFACES

_squared_euclidean_distances2 = T.sqrt(
( dips ** 2).sum(1).reshape(( dips.shape[0], 1)) + ( aux_Y ** 2).sum(1).reshape(
    (1,  aux_Y.shape[0])) - 2 *  dips.dot( aux_Y.T))

_squared_euclidean_distances3 = T.sqrt(
( dips ** 2).sum(1).reshape(( dips.shape[0], 1)) + ( aux_X ** 2).sum(1).reshape(
    (1,  aux_X.shape[0])) - 2 *  dips.dot( aux_X.T))


h3 = T.vertical_stack(
 (dips[:, 0] -  aux_Y[:, 0].reshape(( aux_Y[:, 0].shape[0], 1))).T,
(dips[:, 1] -  aux_Y[:, 1].reshape(( aux_Y[:, 1].shape[0], 1))).T
)


h_j =  (dips[:, 0] -  aux_X[:, 0].reshape(( aux_X[:, 0].shape[0], 1))).T


h4 = T.vertical_stack(
(dips[:, 0] -  aux_X[:, 0].reshape(( aux_X[:, 0].shape[0], 1))).T,
(dips[:, 1] -  aux_X[:, 1].reshape(( aux_X[:, 1].shape[0], 1))).T)


r_3 = T.tile(_squared_euclidean_distances2, (2, 1))  # Careful with the number of dimensions
r_4 = T.tile(_squared_euclidean_distances3, (2, 1))  # Careful with the number of dimensions

_ans_d1_3 = (r_3 <  a) * (
-7 * ( a - r_3) ** 3 * r_3 * (8 *  a ** 2 + 9 *  a * r_3 + 3 * r_3 ** 2) * 1) / (4 *  a ** 7)

_ans_d1_4 = (r_4 <  a) * (
-7 * ( a - r_4) ** 3 * r_4 * (8 *  a ** 2 + 9 *  a * r_4 + 3 * r_4 ** 2) * 1) / (4 *  a ** 7)

_C_GI =( h3 / r_3 *  _ans_d1_3 - h4 / r_4 *  _ans_d1_4).T

_f_CGI = theano.function([dips, aux_X, aux_Y], _C_GI)
#======================
print (r_3.eval({dips: dips2, aux_Y:aux_Y2}))
print (r_4.eval({dips: dips2, aux_X:aux_X2}))
print (h3.eval({dips: dips2, aux_Y:aux_Y2}))
print (h_j.eval({dips: dips2, aux_X:aux_X2}))
print ("camion")

print (h4.eval({dips: dips2, aux_X:aux_X2}))
print (_C_GI.eval({dips: dips2, aux_X:aux_X2, aux_Y:aux_Y2}))

aux [[ 1.  7.]
 [ 1.  7.]
 [ 1.  7.]
 [ 1.  1.]
 [ 1.  1.]] [[ 5.  7.]
 [ 6.  7.]
 [ 9.  8.]
 [ 5.  1.]
 [ 9.  1.]] (5, 2) (5, 2)
dips [[ 2.  4.]
 [ 6.  3.]]
[[ 4.24264069  5.          8.06225775  4.24264069  7.61577311]
 [ 4.12310563  4.          5.83095189  2.23606798  3.60555128]
 [ 4.24264069  5.          8.06225775  4.24264069  7.61577311]
 [ 4.12310563  4.          5.83095189  2.23606798  3.60555128]]
[[ 3.16227766  3.16227766  3.16227766  3.16227766  3.16227766]
 [ 6.40312424  6.40312424  6.40312424  5.38516481  5.38516481]
 [ 3.16227766  3.16227766  3.16227766  3.16227766  3.16227766]
 [ 6.40312424  6.40312424  6.40312424  5.38516481  5.38516481]]
[[-3. -4. -7. -3. -7.]
 [ 1.  0. -3.  1. -3.]
 [-3. -3. -4.  3.  3.]
 [-4. -4. -5.  2.  2.]]
[[ 1.  1.  1.  1.  1.]
 [ 5.  5.  5.  5.  5.]]
camion
[[ 1.  1.  1.  1.  1.]
 [ 5.  5.  5.  5.  5.]
 [-3. -3. -3.  3.  3.]
 [-4. -4. -4.  2.  2.]]
[[  1.27950673e-01  -2.32146843e-02  -1.51334127e-01   9.28587371e-02]
 [  8.56498181e-02  -0.00

In [920]:
T.horizontal_stack?

In [1046]:
_f_CGI(dips2,aux_X2,aux_Y2)

array([[  1.27950673e-01,  -2.32146843e-02,  -1.51334127e-01,
          9.28587371e-02],
       [  8.56498181e-02,  -0.00000000e+00,  -1.97592137e-01,
          1.10425240e-01],
       [  6.98212002e-02,   6.38618306e-05,  -2.09463600e-01,
          1.06436384e-04],
       [  1.27950673e-01,  -1.36420720e-01,   1.51334127e-01,
         -2.80580506e-01],
       [  6.98212002e-02,   1.39156030e-01,   2.09463600e-01,
         -8.76113098e-02]])